# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "earthquake-notifier"

[default.build]
[default.build.parameters]
cached = true
parallel = true
beta_features = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-77ul7ns4tpc8"
s3_prefix = "earthquake-notifier"
region = "eu-west-1"
parameter_overrides = "PrefixParam=\"earthquake-notifier\" EventBusNameParam=\"default\" CenterLatLonParam=\"37.5079,15.0830\" MinMagnitudeParam=\"3.5\" MaxDistanceMetersParam=\"2000000\" EmailAddressParam=\"lucianomammino@gmail.com\""
image_repositories = []

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true
beta_features = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
